/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CompartilharRouteImport } from './routes/compartilhar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ReceitaRecipeIdRouteImport } from './routes/receita.$recipeId'
import { Route as ReceitaRecipeIdAvaliarRouteImport } from './routes/receita.$recipeId.avaliar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CompartilharRoute = CompartilharRouteImport.update({
  id: '/compartilhar',
  path: '/compartilhar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitaRecipeIdRoute = ReceitaRecipeIdRouteImport.update({
  id: '/receita/$recipeId',
  path: '/receita/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitaRecipeIdAvaliarRoute = ReceitaRecipeIdAvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => ReceitaRecipeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/compartilhar': typeof CompartilharRoute
  '/entrar': typeof EntrarRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/ranking': typeof RankingRoute
  '/receita/$recipeId': typeof ReceitaRecipeIdRouteWithChildren
  '/receita/$recipeId/avaliar': typeof ReceitaRecipeIdAvaliarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/compartilhar': typeof CompartilharRoute
  '/entrar': typeof EntrarRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/ranking': typeof RankingRoute
  '/receita/$recipeId': typeof ReceitaRecipeIdRouteWithChildren
  '/receita/$recipeId/avaliar': typeof ReceitaRecipeIdAvaliarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/compartilhar': typeof CompartilharRoute
  '/entrar': typeof EntrarRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/ranking': typeof RankingRoute
  '/receita/$recipeId': typeof ReceitaRecipeIdRouteWithChildren
  '/receita/$recipeId/avaliar': typeof ReceitaRecipeIdAvaliarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buscar'
    | '/cadastro'
    | '/compartilhar'
    | '/entrar'
    | '/perfil'
    | '/publicar'
    | '/ranking'
    | '/receita/$recipeId'
    | '/receita/$recipeId/avaliar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/buscar'
    | '/cadastro'
    | '/compartilhar'
    | '/entrar'
    | '/perfil'
    | '/publicar'
    | '/ranking'
    | '/receita/$recipeId'
    | '/receita/$recipeId/avaliar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buscar'
    | '/cadastro'
    | '/compartilhar'
    | '/entrar'
    | '/perfil'
    | '/publicar'
    | '/ranking'
    | '/receita/$recipeId'
    | '/receita/$recipeId/avaliar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuscarRoute: typeof BuscarRoute
  CadastroRoute: typeof CadastroRoute
  CompartilharRoute: typeof CompartilharRoute
  EntrarRoute: typeof EntrarRoute
  PerfilRoute: typeof PerfilRoute
  PublicarRoute: typeof PublicarRoute
  RankingRoute: typeof RankingRoute
  ReceitaRecipeIdRoute: typeof ReceitaRecipeIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compartilhar': {
      id: '/compartilhar'
      path: '/compartilhar'
      fullPath: '/compartilhar'
      preLoaderRoute: typeof CompartilharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receita/$recipeId': {
      id: '/receita/$recipeId'
      path: '/receita/$recipeId'
      fullPath: '/receita/$recipeId'
      preLoaderRoute: typeof ReceitaRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receita/$recipeId/avaliar': {
      id: '/receita/$recipeId/avaliar'
      path: '/avaliar'
      fullPath: '/receita/$recipeId/avaliar'
      preLoaderRoute: typeof ReceitaRecipeIdAvaliarRouteImport
      parentRoute: typeof ReceitaRecipeIdRoute
    }
  }
}

interface ReceitaRecipeIdRouteChildren {
  ReceitaRecipeIdAvaliarRoute: typeof ReceitaRecipeIdAvaliarRoute
}

const ReceitaRecipeIdRouteChildren: ReceitaRecipeIdRouteChildren = {
  ReceitaRecipeIdAvaliarRoute: ReceitaRecipeIdAvaliarRoute,
}

const ReceitaRecipeIdRouteWithChildren = ReceitaRecipeIdRoute._addFileChildren(
  ReceitaRecipeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuscarRoute: BuscarRoute,
  CadastroRoute: CadastroRoute,
  CompartilharRoute: CompartilharRoute,
  EntrarRoute: EntrarRoute,
  PerfilRoute: PerfilRoute,
  PublicarRoute: PublicarRoute,
  RankingRoute: RankingRoute,
  ReceitaRecipeIdRoute: ReceitaRecipeIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
